version: '3.12'

services:
  app:
    build:
      context: app
    env_file:
      - "app/.env.docker"
    container_name: fastapi_app
    restart: "always"
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - "app/.env.docker"
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
